name: gesticom
description: "Une application windows qui va permettre de faire la gestion des clients des employés et des rapports quotidiens"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: "3.7.2"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.8.0
  sqflite_common: ^2.5.5
  sqflite: ^2.2.0
  sqflite_common_ffi: ^2.3.5
  sqflite_common_ffi_web: ^1.0.0
  logger: ^2.0.2
  intl: ^0.20.2
  printing: ^5.6.0 # Added printing package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
